require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  'Calendars',
  'CalendarsWriteOnly',
  'Camera',
  'Contacts',
  'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
  'Motion',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
  'Siri',
  'SpeechRecognition',
  'StoreKit',
])

target 'my_augmented_app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # To enable Hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-sceneform', :path => '../node_modules/@sceneview/react-native-sceneform'

  target 'my_augmented_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  # Post-install setup
  post_install do |installer|
    react_native_post_install(installer)
    # Ensure that you have the following line for Flipper setup
    flipper_post_install(installer)
    # Apply Xcode 12.5 M1 post-install workaround
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
